services:
  watchtower:
    image: ghcr.io/containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g: Europe/London
      - TZ=${TZ}
      - WATCHTOWER_ROLLING_RESTART=${WATCHTOWER_ROLLING_RESTART}
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_DEBUG=${WATCHTOWER_DEBUG}
      - WATCHTOWER_INCLUDE_STOPPED=${WATCHTOWER_INCLUDE_STOPPED}
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL}
      - WATCHTOWER_RUN_ONCE=${WATCHTOWER_RUN_ONCE}
      - WATCHTOWER_LABEL_ENABLE=true
