services:
  qnetd:
    container_name: proxmox-qdevice
    image: ghcr.io/merrymeng/proxmox-qdevice:v2.0
    ports:
      - "22:22"
      - "5403:5403"
    environment:
      - NEW_ROOT_PASSWORD=${ROOT_PASS}
    volumes:
      - /run/sshd
      - proxmox-qdevice_data:/etc/corosync
    restart: unless-stopped
    hostname: ${HOSTNAME}
    networks:
      vlan:
        ipv4_address: ${STATIC_IP}

networks:
 vlan:
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_DEVICE}
    ipam:
       driver: default
       config:
        - subnet: ${SUBNET}
          ip_range: "${STATIC_IP}/32"
          gateway: ${GATEWAY}

volumes:
  proxmox-qdevice_data:
