---
version: "3.7"
services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:stable
    mac_address: ${MAC_ADDRESS}
    environment:
      - TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale/state:/var/lib/tailscale
      - /portainer/Files/AppData/Config/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    hostname: ${HOSTNAME}
    networks:
      vlan:
        ipv4_address: ${STATIC_IP}

networks:
 vlan:
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_DEVICE}
    ipam:
       driver: default
       config:
        - subnet: ${SUBNET}
          ip_range: "${STATIC_IP}/32"
          gateway: ${GATEWAY}
