name: portainer-edge
services:
    agent:
        labels:
            - com.centurylinklabs.watchtower.enable=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /var/lib/docker/volumes:/var/lib/docker/volumes
            - /:/host:ro
            - portainer_agent_data:/data
        restart: always
        environment:
            - EDGE=1
            - EDGE_ID=$EDGE_ID
            - EDGE_KEY=$EDGE_KEY
            - EDGE_INSECURE_POLL=1
        container_name: portainer_edge_agent
        image: portainer/agent:latest
volumes:
    portainer_agent_data:
        external: true
        name: portainer_agent_data
